#!/usr/bin/env bash
# Bellkeeper 环境变量初始化脚本
# 使用: source config/bellkeeper-init.sh [profile]
# profile: production | development (default)
#
# CLAUDE.md §2.4: 新增环境变量必须同步到此文件。

set -euo pipefail

BELLKEEPER_PROFILE="${1:-development}"

# ── 核心服务 ──────────────────────────────────────────────
export BELLKEEPER_SERVER_HOST="${BELLKEEPER_SERVER_HOST:-0.0.0.0}"
export BELLKEEPER_SERVER_PORT="${BELLKEEPER_SERVER_PORT:-8080}"
export BELLKEEPER_SERVER_MODE="${BELLKEEPER_SERVER_MODE:-debug}"
export BELLKEEPER_SERVER_API_KEY="${BELLKEEPER_SERVER_API_KEY:-}"
export BELLKEEPER_SERVER_SHUTDOWN_TIMEOUT="${BELLKEEPER_SERVER_SHUTDOWN_TIMEOUT:-10}"

# ── 数据库 ────────────────────────────────────────────────
export BELLKEEPER_DATABASE_DRIVER="${BELLKEEPER_DATABASE_DRIVER:-postgres}"
export BELLKEEPER_DATABASE_HOST="${BELLKEEPER_DATABASE_HOST:-localhost}"
export BELLKEEPER_DATABASE_PORT="${BELLKEEPER_DATABASE_PORT:-5432}"
export BELLKEEPER_DATABASE_NAME="${BELLKEEPER_DATABASE_NAME:-bellkeeper}"
export BELLKEEPER_DATABASE_USER="${BELLKEEPER_DATABASE_USER:-bellkeeper}"
export BELLKEEPER_DATABASE_PASSWORD="${BELLKEEPER_DATABASE_PASSWORD:-}"
export BELLKEEPER_DATABASE_SSLMODE="${BELLKEEPER_DATABASE_SSLMODE:-disable}"
export BELLKEEPER_DATABASE_AUTO_MIGRATE="${BELLKEEPER_DATABASE_AUTO_MIGRATE:-true}"

# ── NATS (JetStream 事件总线) ────────────────────────────
export BELLKEEPER_NATS_URL="${BELLKEEPER_NATS_URL:-nats://sp-nats:4222}"
export BELLKEEPER_NATS_STREAMS_NOTIFICATIONS="${BELLKEEPER_NATS_STREAMS_NOTIFICATIONS:-notifications}"
export BELLKEEPER_NATS_STREAMS_KNOWLEDGE="${BELLKEEPER_NATS_STREAMS_KNOWLEDGE:-knowledge}"
export BELLKEEPER_NATS_STREAMS_LLM="${BELLKEEPER_NATS_STREAMS_LLM:-llm}"
export BELLKEEPER_NATS_STREAMS_MATRIX="${BELLKEEPER_NATS_STREAMS_MATRIX:-matrix}"
export BELLKEEPER_NATS_STREAMS_SYSTEM="${BELLKEEPER_NATS_STREAMS_SYSTEM:-system}"
export BELLKEEPER_NATS_STREAMS_LOGS="${BELLKEEPER_NATS_STREAMS_LOGS:-logs}"

# ── Redis ─────────────────────────────────────────────────
export BELLKEEPER_REDIS_HOST="${BELLKEEPER_REDIS_HOST:-sp-redis}"
export BELLKEEPER_REDIS_PORT="${BELLKEEPER_REDIS_PORT:-6379}"
export BELLKEEPER_REDIS_DB="${BELLKEEPER_REDIS_DB:-0}"
export BELLKEEPER_REDIS_PASSWORD="${BELLKEEPER_REDIS_PASSWORD:-}"

# ── Matrix ────────────────────────────────────────────────
export BELLKEEPER_MATRIX_HOMESERVER_URL="${BELLKEEPER_MATRIX_HOMESERVER_URL:-https://matrix.singll.net}"
export BELLKEEPER_MATRIX_BOT_USER_ID="${BELLKEEPER_MATRIX_BOT_USER_ID:-@bellkeeper:matrix.singll.net}"
export BELLKEEPER_MATRIX_BOT_ACCESS_TOKEN="${BELLKEEPER_MATRIX_BOT_ACCESS_TOKEN:-}"
export BELLKEEPER_MATRIX_DEVICE_ID="${BELLKEEPER_MATRIX_DEVICE_ID:-BELLKEEPER_KEEPER}"
export BELLKEEPER_MATRIX_SYNC_TIMEOUT="${BELLKEEPER_MATRIX_SYNC_TIMEOUT:-30000}"
export BELLKEEPER_MATRIX_COMMAND_PREFIX="${BELLKEEPER_MATRIX_COMMAND_PREFIX:-,！}"
export BELLKEEPER_MATRIX_MAX_RETRY="${BELLKEEPER_MATRIX_MAX_RETRY:-3}"
export BELLKEEPER_MATRIX_ADMIN_USERS="${BELLKEEPER_MATRIX_ADMIN_USERS:-@singll:matrix.singll.net}"

# ── Matrix AI Agent ───────────────────────────────────────
export BELLKEEPER_MATRIX_AGENT_ENABLED="${BELLKEEPER_MATRIX_AGENT_ENABLED:-false}"
export BELLKEEPER_MATRIX_AGENT_MODEL="${BELLKEEPER_MATRIX_AGENT_MODEL:-pool-chat-balanced}"
export BELLKEEPER_MATRIX_AGENT_MAX_TURNS_PER_HOUR="${BELLKEEPER_MATRIX_AGENT_MAX_TURNS_PER_HOUR:-300}"
export BELLKEEPER_MATRIX_AGENT_SESSION_TTL="${BELLKEEPER_MATRIX_AGENT_SESSION_TTL:-30m}"
export BELLKEEPER_MATRIX_AGENT_MAX_TOOL_ITERATIONS="${BELLKEEPER_MATRIX_AGENT_MAX_TOOL_ITERATIONS:-5}"

# ── Meilisearch ──────────────────────────────────────────
export BELLKEEPER_MEILISEARCH_URL="${BELLKEEPER_MEILISEARCH_URL:-http://sp-meilisearch:7700}"
export BELLKEEPER_MEILISEARCH_API_KEY="${BELLKEEPER_MEILISEARCH_API_KEY:-}"
export BELLKEEPER_MEILISEARCH_INDEX="${BELLKEEPER_MEILISEARCH_INDEX:-knowledge_chunks}"

# ── Memos ─────────────────────────────────────────────────
export BELLKEEPER_MEMOS_ENABLED="${BELLKEEPER_MEMOS_ENABLED:-false}"
export BELLKEEPER_MEMOS_BASE_URL="${BELLKEEPER_MEMOS_BASE_URL:-}"
export BELLKEEPER_MEMOS_API_TOKEN="${BELLKEEPER_MEMOS_API_TOKEN:-}"

# ── LLM 代理池 ───────────────────────────────────────────
export BELLKEEPER_LLM_PROXY_ENABLED="${BELLKEEPER_LLM_PROXY_ENABLED:-true}"
export BELLKEEPER_LLM_PROXY_DEFAULT_TIMEOUT="${BELLKEEPER_LLM_PROXY_DEFAULT_TIMEOUT:-60}"
export BELLKEEPER_LLM_PROXY_MAX_RETRIES="${BELLKEEPER_LLM_PROXY_MAX_RETRIES:-3}"
export BELLKEEPER_LLM_PROXY_DEFAULT_BUCKET_RPM="${BELLKEEPER_LLM_PROXY_DEFAULT_BUCKET_RPM:-1000}"

# ── RSS 抓取 ─────────────────────────────────────────────
export BELLKEEPER_RSS_FETCHER_ENABLED="${BELLKEEPER_RSS_FETCHER_ENABLED:-true}"
export BELLKEEPER_RSS_FETCHER_CHECK_INTERVAL="${BELLKEEPER_RSS_FETCHER_CHECK_INTERVAL:-60}"
export BELLKEEPER_RSS_FETCHER_RSSHUB_BASE_URL="${BELLKEEPER_RSS_FETCHER_RSSHUB_BASE_URL:-}"

# ── 爬取队列 ─────────────────────────────────────────────
export BELLKEEPER_CRAWL_QUEUE_ENABLED="${BELLKEEPER_CRAWL_QUEUE_ENABLED:-true}"
export BELLKEEPER_CRAWL_QUEUE_MAX_RETRIES="${BELLKEEPER_CRAWL_QUEUE_MAX_RETRIES:-4}"
export BELLKEEPER_CRAWL_QUEUE_DOMAIN_PENDING_CAP="${BELLKEEPER_CRAWL_QUEUE_DOMAIN_PENDING_CAP:-5000}"

# ── 日志中心 ─────────────────────────────────────────────
export BELLKEEPER_LOG_CENTER_RETENTION_DAYS="${BELLKEEPER_LOG_CENTER_RETENTION_DAYS:-30}"
export BELLKEEPER_LOG_CENTER_CLEANUP_INTERVAL_HRS="${BELLKEEPER_LOG_CENTER_CLEANUP_INTERVAL_HRS:-24}"

# ── 知识库 ───────────────────────────────────────────────
export BELLKEEPER_KNOWLEDGE_ENABLED="${BELLKEEPER_KNOWLEDGE_ENABLED:-true}"
export BELLKEEPER_KNOWLEDGE_BASE_PATH="${BELLKEEPER_KNOWLEDGE_BASE_PATH:-/mnt/knowledge}"
export BELLKEEPER_KNOWLEDGE_SCAN_INTERVAL="${BELLKEEPER_KNOWLEDGE_SCAN_INTERVAL:-300}"

# ── 文件摄入 (Firecrawl / Trafilatura) ──────────────────
export BELLKEEPER_FILE_INGESTION_ENABLED="${BELLKEEPER_FILE_INGESTION_ENABLED:-true}"
export BELLKEEPER_FILE_INGESTION_BASE_PATH="${BELLKEEPER_FILE_INGESTION_BASE_PATH:-/mnt/knowledge}"

# ── 每日报告 ─────────────────────────────────────────────
export BELLKEEPER_DAILY_REPORT_ENABLED="${BELLKEEPER_DAILY_REPORT_ENABLED:-true}"
export BELLKEEPER_DAILY_REPORT_WATCHDOG_ENABLED="${BELLKEEPER_DAILY_REPORT_WATCHDOG_ENABLED:-true}"

# ── 凭据加密 ─────────────────────────────────────────────
# BELLKEEPER_CREDENTIAL_KEY 应设为 32 字节 hex 字符串；
# 未设置时凭据以明文存储（开发环境可接受，生产环境必设）

# ── 安全开关 ─────────────────────────────────────────────
# BELLKEEPER_ALLOW_NOAUTH 设 "false" 阻止以 noauth 模式启动

if [ "$BELLKEEPER_PROFILE" = "production" ]; then
  if [ -z "${BELLKEEPER_SERVER_API_KEY:-}" ]; then
    echo "[WARN] BELLKEEPER_SERVER_API_KEY is empty — API auth disabled" >&2
  fi
  if [ -z "${BELLKEEPER_DATABASE_PASSWORD:-}" ]; then
    echo "[WARN] BELLKEEPER_DATABASE_PASSWORD is empty" >&2
  fi
fi

echo "[bellkeeper-init] profile=$BELLKEEPER_PROFILE — environment variables loaded"
